import type { CatalogKind } from "../adapter.js";
// Every query is scoped to accessible objects; filtering/pagination is appended by the adapter.
export const postgresCatalog: Record<CatalogKind, string> = {
  constraintColumns: `SELECT n.nspname AS schema,c.relname AS table_name,k.conname AS name,a.attname AS column_name,x.position FROM pg_constraint k JOIN pg_class c ON c.oid=k.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace CROSS JOIN LATERAL unnest(k.conkey) WITH ORDINALITY AS x(attnum,position) JOIN pg_attribute a ON a.attrelid=c.oid AND a.attnum=x.attnum WHERE has_table_privilege(c.oid,'SELECT')`,
  indexColumns: `SELECT n.nspname AS schema,t.relname AS table_name,c.relname AS name,pg_get_indexdef(c.oid,x.position::integer,true) AS column_name,x.position FROM pg_index i JOIN pg_class c ON c.oid=i.indexrelid JOIN pg_class t ON t.oid=i.indrelid JOIN pg_namespace n ON n.oid=t.relnamespace CROSS JOIN LATERAL unnest(i.indkey) WITH ORDINALITY AS x(attnum,position) WHERE has_table_privilege(t.oid,'SELECT')`,
  materializedViews: `SELECT n.nspname AS schema,c.relname AS name,c.relkind AS kind,pg_get_viewdef(c.oid,true) AS definition FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relkind='m' AND has_table_privilege(c.oid,'SELECT')`,

  schemas: `SELECT n.nspname AS schema FROM pg_catalog.pg_namespace n WHERE has_schema_privilege(n.oid,'USAGE') AND n.nspname NOT LIKE 'pg_%' AND n.nspname <> 'information_schema'`,
  tables: `SELECT n.nspname AS schema,c.relname AS name,c.relkind AS kind FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relkind IN ('r','p') AND has_table_privilege(c.oid,'SELECT')`,
  columns: `SELECT table_schema AS schema,table_name AS name,column_name,ordinal_position,data_type,udt_name,character_maximum_length,numeric_precision,numeric_scale,is_nullable,column_default,is_identity,identity_generation,is_generated,generation_expression FROM information_schema.columns`,
  views: `SELECT n.nspname AS schema,c.relname AS name,c.relkind AS kind,pg_get_viewdef(c.oid,true) AS definition FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relkind IN ('v','m') AND has_table_privilege(c.oid,'SELECT')`,
  indexes: `SELECT n.nspname AS schema,t.relname AS table_name,c.relname AS name,pg_get_indexdef(c.oid) AS definition FROM pg_index i JOIN pg_class c ON c.oid=i.indexrelid JOIN pg_class t ON t.oid=i.indrelid JOIN pg_namespace n ON n.oid=t.relnamespace WHERE has_table_privilege(t.oid,'SELECT')`,
  constraints: `SELECT n.nspname AS schema,c.relname AS table_name,k.conname AS name,k.contype AS kind,pg_get_constraintdef(k.oid,true) AS definition FROM pg_constraint k JOIN pg_class c ON c.oid=k.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE has_table_privilege(c.oid,'SELECT')`,
  sequences: `SELECT schemaname AS schema,sequencename AS name,data_type,start_value,min_value,max_value,increment_by,cycle,cache_size FROM pg_sequences WHERE has_sequence_privilege(format('%I.%I',schemaname,sequencename),'USAGE,SELECT')`,
  triggers: `SELECT n.nspname AS schema,c.relname AS table_name,t.tgname AS name,pg_get_triggerdef(t.oid,true) AS definition FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE NOT t.tgisinternal AND has_table_privilege(c.oid,'SELECT')`,
  routines: `SELECT n.nspname AS schema,p.proname AS name,p.oid::text AS identity,p.prokind AS kind,pg_get_function_identity_arguments(p.oid) AS arguments FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE p.prokind IN ('f','p') AND has_schema_privilege(n.oid,'USAGE') AND has_function_privilege(p.oid,'EXECUTE')`,
  source: `SELECT n.nspname AS schema,p.proname AS name,p.oid::text AS identity,pg_get_function_identity_arguments(p.oid) AS arguments,pg_get_functiondef(p.oid) AS definition FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE p.prokind IN ('f','p') AND has_schema_privilege(n.oid,'USAGE') AND has_function_privilege(p.oid,'EXECUTE')`,
  dependencies: `SELECT n.nspname AS schema,c.relname AS name,pg_describe_object(d.classid,d.objid,d.objsubid) AS dependent,d.deptype FROM pg_depend d JOIN pg_class c ON c.oid=d.refobjid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE d.refclassid='pg_class'::regclass AND has_table_privilege(c.oid,'SELECT')`,
  objects: `SELECT n.nspname AS schema,c.relname AS name,c.relkind AS kind FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relkind IN ('r','p','v','m','S','i') AND has_schema_privilege(n.oid,'USAGE')`,
  enums: `SELECT n.nspname AS schema,t.typname AS name,e.enumlabel AS label,e.enumsortorder AS ordinal FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace JOIN pg_enum e ON e.enumtypid=t.oid WHERE has_schema_privilege(n.oid,'USAGE')`,
  extensions: `SELECT n.nspname AS schema,e.extname AS name,e.extversion AS version FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace WHERE has_schema_privilege(n.oid,'USAGE')`,
  synonyms: `SELECT NULL::text AS schema,NULL::text AS name WHERE false`,
};
